#!/usr/bin/env python3
"""Rebuild dataset.jsonl from the 30 source files.

Run from the repository root:

    python build.py

dataset.jsonl is the complete training set: every record from every source
file (3,000 records), regenerated in full on each run. Nothing is held out
for evaluation here.

eval.jsonl is NOT regenerated by this script. It is hand-curated held-out
data -- records that exist in no source file, so the model has never seen
them during training. Edit eval.jsonl directly to add or change evaluation
records. validate.py enforces that no prompt appears in both files, which is
the "the model has not seen the eval data" guarantee.

(The previous prompt-grouped train/eval split is no longer used. It existed
to prevent leakage when eval was drawn from the source library. Now that eval
is hand-curated and separate from the source library, leakage is prevented by
construction, and validate.py's no-overlap check guards against accidental
prompt matches.)
"""
import glob
from pathlib import Path

rows = []
files = sorted(glob.glob("*/*/*.jsonl"))
for path in files:
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if line:
            rows.append(line)

Path("dataset.jsonl").write_bytes(("\n".join(rows) + "\n").encode("utf-8"))

print(f"source files  : {len(files)} files")
print(f"dataset.jsonl : {len(rows)} records (full training set)")
print("eval.jsonl    : not regenerated -- hand-curated held-out data (edit directly)")
print("               validate.py checks that no eval prompt appears in dataset.jsonl")